const Q=[
{id:1,t:"Начало охоты",p:"Красная площадь",lat:55.7539,lng:37.6208,x:50,s:"Начинаем там, где Москва чаще всего оказывается на открытках. Сегодня задача — смотреть не на открытку, а на детали.",q:"Осмотрись вокруг и найди деталь, которая выглядит старше окружающего пространства.",k:"obs",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Red%20Square%20in%20Moscow%2002.jpg"},
{id:2,t:"Посмотри вверх",p:"Варварка",lat:55.7522,lng:37.6258,x:100,s:"Варварка — одна из старейших улиц Москвы. Её название связано с церковью Святой Варвары.",q:"Почему улица называется Варваркой?",k:"quiz",a:["В честь варягов","В честь Святой Варвары","Так называли торговцев"],c:1},
{id:3,t:"След иностранцев",p:"Старый Английский двор",lat:55.7520,lng:37.6267,x:200,s:"В этих палатах находилось английское торговое представительство. Представь Москву XVI века: здесь пересекались местные купцы и иностранные торговцы.",q:"Какую роль Старый Английский двор играл в истории Москвы?",k:"quiz",a:["Военную крепость","Торговое представительство","Царскую резиденцию","Монастырь"],c:1,secret:1,img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/7079.2._%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0._%D0%A1%D1%82%D0%B0%D1%80%D1%8B%D0%B9_%D0%90%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9_%D0%B4%D0%B2%D0%BE%D1%80.jpg"},
{id:4,t:"Дом, из которого вышла династия",p:"Палаты бояр Романовых",lat:55.7526,lng:37.6270,x:100,s:"С этим местом связан род Романовых. Здесь особенно легко представить, насколько тесным был средневековый город.",q:"Как звали первого царя из династии Романовых?",k:"quiz",a:["Иван","Алексей","Михаил","Фёдор"],c:2,img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/7032.2._Moscow._Varvarka_Street%2C_10_building_1.jpg"},
{id:5,t:"Найди лишнее",p:"Знаменский монастырь",lat:55.7530,lng:37.6264,x:75,s:"Перед тобой ансамбль, где разные эпохи буквально стоят рядом.",q:"Найди архитектурную деталь, которая визуально выбивается из общего ансамбля.",k:"obs"},
{id:6,t:"Город, которого больше нет",p:"Зарядье",lat:55.7521,lng:37.6285,x:100,s:"Здесь когда-то был старый городской район, затем появилась гостиница «Россия», а сегодня — парк.",q:"Что находилось здесь до современного парка?",k:"quiz",a:["Гостиница «Россия»","Царский ипподром","Главный вокзал"],c:0},
{id:7,t:"Поймай три эпохи",p:"Парящий мост",lat:55.7508,lng:37.6250,x:100,s:"С высоты видно сразу несколько слоёв Москвы.",q:"Найди Кремль, Москву-реку и современную панораму. Затем нажми «Нашёл всё».",k:"obs"},
{id:8,t:"Найди исчезнувшую Москву",p:"Китайгородская стена",lat:55.7557,lng:37.6274,x:125,s:"Китайгородская стена была построена в 1535–1538 годах. Сегодня сохранились лишь отдельные фрагменты.",q:"Найди сохранившийся фрагмент стены и сравни его масштаб с современным городом.",k:"obs"},
{id:9,t:"Анна в Углу",p:"Церковь Анны в Углу",lat:55.7547,lng:37.6286,x:100,s:"Название храма связано с его положением у угла старой линии укреплений Китай-города.",q:"Почему храм называют «Анна в Углу»?",k:"quiz",a:["Из-за имени основателя","Из-за положения у угла стены","Из-за формы купола"],c:1,secret:1},
{id:10,t:"Охотник за Москвой",p:"Финал",lat:55.7547,lng:37.6286,x:150,s:"Ты прошёл маршрут и собрал собственную карту памяти старой Москвы.",q:"Охота завершена.",k:"finish"}];
let S=load(),me=null,map=null,promptEvent=null;
const D={m:0,x:0,sec:0,paid:false};
function load(){try{return {...D,...JSON.parse(localStorage.getItem("cq03")||"{}")}}catch(e){return {...D}}}
function save(){localStorage.setItem("cq03",JSON.stringify(S))}
function shell(c){app.innerHTML=`<main><header><b>CITY QUEST</b><span>${S.x} XP</span></header>${c}<footer>CITY QUEST · v0.3</footer></main>`}
function toast(t){let z=document.getElementById("toast");z.textContent=t;z.className="show";setTimeout(()=>z.className="",1800)}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();promptEvent=e});
async function install(){if(promptEvent){promptEvent.prompt();promptEvent=null}}
function home(){shell(`<section class="hero"><small>ПЕРВАЯ ОХОТА</small><h1>Тайны<br>старой Москвы</h1><p>Пеший квест, который превращает прогулку в охоту за историей.</p><div class="card"><div class="cover"><b>10</b><span>МИССИЙ</span></div><div class="chips"><i>🚶 ~4 км</i><i>⏱ 1,5–2 часа</i><i>🔎 2 секрета</i></div><button onclick="start()">Начать охоту</button><button class="dark" onclick="about()">Как это работает</button>${promptEvent?'<button class="dark" onclick="install()">📱 Установить</button>':''}</div></section>`)}
function about(){shell(`<small>CITY QUEST</small><h1>Прогулка<br>как игра.</h1><div class="card"><p>📍 Иди к точке — карта и GPS.</p><p>👀 Смотри вокруг — задания на месте.</p><p>🧠 Разгадывай — вопросы и секреты.</p><p>🏆 Собирай XP — финальный результат.</p><button onclick="home()">Назад</button></div>`)}
function start(){S={...D};save();route()}
function route(){if(S.m>=10)return finish();let q=Q[S.m];shell(`<small>МАРШРУТ · ${q.id}/10</small><h2>Тайны старой Москвы</h2><div id="map"></div><p id="distance">${distance()}</p><div class="card"><small>СЛЕДУЮЩАЯ ТОЧКА</small><h3>${q.p}</h3><button onclick="mission()">Открыть миссию</button><button class="dark" onclick="locate()">📍 Моё местоположение</button><button class="dark" onclick="share()">↗ Поделиться</button></div>`);initMap()}
function initMap(){if(!window.L)return;map=L.map("map").setView([55.7535,37.6265],15);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(map);Q.forEach((q,i)=>{if(i<=S.m+1)L.marker([q.lat,q.lng]).addTo(map).bindPopup(`<b>${q.id}. ${q.p}</b>`)});if(me)L.marker([me.lat,me.lng]).addTo(map).bindPopup("Ты здесь")}
function locate(){if(!navigator.geolocation)return toast("GPS недоступен");navigator.geolocation.getCurrentPosition(p=>{me={lat:p.coords.latitude,lng:p.coords.longitude};route()},()=>toast("Разреши GPS в Safari"),{enableHighAccuracy:true,timeout:10000})}
function distance(){if(!me)return"GPS пока не включён.";let q=Q[S.m],d=dist(me.lat,me.lng,q.lat,q.lng);return d<1?`До точки ~${Math.round(d*1000)} м`:`До точки ~${d.toFixed(1)} км`}
function dist(a,b,c,d){let R=6371,r=x=>x*Math.PI/180,x=r(c-a),y=r(d-b),v=Math.sin(x/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(v))}
function mission(){if(S.m>=3&&!S.paid)return pay();let q=Q[S.m],img=q.img?`<figure><img src="${q.img}" onerror="this.parentNode.remove()"><figcaption>Фото: Wikimedia Commons</figcaption></figure>`:"";let a=`<small>МИССИЯ ${q.id}/10 · ${q.p}</small><h1>${q.t}</h1><div class="bar"><i style="width:${q.id*10}%"></i></div>${img}<div class="card"><p class="story">${q.s}</p><button class="dark" onclick="speak()">🔊 Послушать историю</button><p class="question">${q.q}</p>`;if(q.k==="quiz")a+=`<div class="answers">${q.a.map((x,i)=>`<button class="answer" onclick="ans(${i})">${String.fromCharCode(65+i)} — ${x}</button>`).join("")}</div>`;else if(q.k==="finish")a+=`<button onclick="finish()">Завершить</button>`;else a+=`<button onclick="complete()">Нашёл / Готово</button>`;a+=`</div><button class="dark" onclick="route()">← К карте</button>`;shell(a)}
function speak(){let q=Q[S.m];if(!("speechSynthesis"in window))return toast("Аудио недоступно");speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(q.t+". "+q.s);u.lang="ru-RU";u.rate=.94;speechSynthesis.speak(u)}
function ans(i){if(i!==Q[S.m].c)return toast("Не угадал — попробуй ещё раз");complete()}
function complete(){let q=Q[S.m];S.x+=q.x;if(q.secret)S.sec++;S.m++;save();if(S.m===3)return pay();if(S.m>=10)return finish();route()}
function pay(){shell(`<small>БЕСПЛАТНАЯ ЧАСТЬ</small><h1>3/10</h1><p>Ты собрал <b>${S.x} XP</b>. Дальше — полный маршрут.</p><div class="card center"><small>ПОЛНЫЙ МАРШРУТ</small><div class="price">249 ₽</div><p>Ещё 7 миссий · 2 секрета · финальный achievement.</p><button onclick="unlock()">Открыть маршрут</button><small>Тестовый режим: реальная оплата пока не подключена.</small></div>`)}
function unlock(){S.paid=true;save();route()}
function finish(){shell(`<section class="finish"><div class="trophy">🏆</div><small>ОХОТНИК ЗА МОСКВОЙ</small><h1>Маршрут<br>пройден.</h1><div class="result"><b>${S.x}</b><span>XP</span><b>${S.sec}/2</b><span>секретов</span></div><div class="card"><p>Ты прошёл все 10 миссий.</p><button onclick="shareResult()">↗ Поделиться результатом</button><button class="dark" onclick="home()">Новый маршрут</button></div></section>`)}
async function share(){if(navigator.share)await navigator.share({title:"CITY QUEST",text:"Попробуй пеший квест по старой Москве.",url:location.href});else{await navigator.clipboard?.writeText(location.href);toast("Ссылка скопирована")}}
async function shareResult(){let text=`Я прошёл CITY QUEST — ${S.x} XP, ${S.sec}/2 секретов!`;if(navigator.share)await navigator.share({title:"CITY QUEST",text,url:location.href});else{await navigator.clipboard?.writeText(text+" "+location.href);toast("Результат скопирован")}}
home();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});